apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service-api
  labels:
    app: database-service-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database-service-api
  template:
    metadata:
      labels:
        app: database-service-api
    spec:
      containers:
        - name: database-service-api
          image: usuario/medsafe-database-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: connectionString
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
