apiVersion: v1
kind: Service
metadata:
  name: database-service-api
spec:
  type: LoadBalancer
  selector:
    app: database-service-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
